[package]
name = "scripting"
version = "0.3.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib"]

[dependencies]
nom = "*"
nix = {version = "*", features = ["user", "process"]}
creche = { version = "*", path = "/home/jeff/rust/crates/creche" }
libc = "*"
